# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConnectPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_connectionPage(object):
    def setupUi(self, connectionPage):
        connectionPage.setObjectName("connectionPage")
        connectionPage.setWindowModality(QtCore.Qt.WindowModal)
        connectionPage.resize(854, 480)
        connectionPage.setMaximumSize(QtCore.QSize(854, 480))
        self.centralwidget = QtWidgets.QWidget(connectionPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(854, 480))
        self.centralwidget.setObjectName("centralwidget")
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setGeometry(QtCore.QRect(750, 440, 101, 31))
        self.okButton.setObjectName("okButton")
        self.connectionTable = QConnectsWidget(self.centralwidget)
        self.connectionTable.setGeometry(QtCore.QRect(0, 49, 854, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.connectionTable.sizePolicy().hasHeightForWidth())
        self.connectionTable.setSizePolicy(sizePolicy)
        self.connectionTable.setMinimumSize(QtCore.QSize(854, 0))
        self.connectionTable.setMaximumSize(QtCore.QSize(854, 480))
        self.connectionTable.setFrameShape(QtWidgets.QFrame.Box)
        self.connectionTable.setLineWidth(1)
        self.connectionTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.connectionTable.setObjectName("connectionTable")
        self.connectionTable.setColumnCount(3)
        self.connectionTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.connectionTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.connectionTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.connectionTable.setHorizontalHeaderItem(2, item)
        self.connectionTable.horizontalHeader().setStretchLastSection(True)
        connectionPage.setCentralWidget(self.centralwidget)

        self.retranslateUi(connectionPage)
        QtCore.QMetaObject.connectSlotsByName(connectionPage)

    def retranslateUi(self, connectionPage):
        _translate = QtCore.QCoreApplication.translate
        connectionPage.setWindowTitle(_translate("connectionPage", "Настройки соединений"))
        self.okButton.setText(_translate("connectionPage", "Ok"))
        item = self.connectionTable.horizontalHeaderItem(0)
        item.setText(_translate("connectionPage", "Имя"))
        item = self.connectionTable.horizontalHeaderItem(1)
        item.setText(_translate("connectionPage", "Адрес"))
        item = self.connectionTable.horizontalHeaderItem(2)
        item.setText(_translate("connectionPage", "Статус"))
from UI.QConnectsWidget import QConnectsWidget
